@echo off
set OutputFile="revision.inc"
echo // Do not edit this file! It generates automatically.> %OutputFile%
FOR /F "usebackq" %%a IN (`git describe --dirty --long`) DO (
	set GitRev=%%a
)
echo const GitRevisionStr = '%GitRev%';>> %OutputFile%