#!/bin/bash

OutputFile="revision.inc"
GitRev=$(git describe --dirty --long)
printf "// Do not edit this file! It generates automatically.\n" > $OutputFile
printf "const\n  GitRevisionStr = '$GitRev';\n" >> $OutputFile
